spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  
logging:
  level:
    root: WARN
    com.shopper: INFO
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info